#' @export
ParamList <- R6::R6Class("ParamList",
                    private = list(
                      params=list(),
                      descriptions=list(alpha="The threshold of statistical significance is {}",
                                        lfcThreshold="The threshold for absolute effect size is {}",
                                        title="The name of the project is '{}'",
                                        top_n_variable="Only use {} genes for unsupervised clustering",
                                        script="The project was generated by '{}'",
                                        showCategory= "Only show top {} enriched categories in plots",
                                        seed="A random seed of {} is used to ensure reproduciblity",
                                        filterFun="{if (is.null(filterFun)) 'Default' else deparse(filterFun)} independent filtering",
                                        baseMeanMin="Discard transcripts with few average counts per sample than {}"
                                        ),
                      defaults=list()
                    ),
                    public = list(
                      initialize = function(defaults=list()) {
                        private$defaults <- defaults
                      },
                      set = function(id, value, description="", div=TRUE) {
                        if (missing(value)) {
                          if (id %in% names(private$defaults)) {
                            value <- private$defaults[[id]]
                          } else {
                            stop("Attempt to set '", id, "' but no value or default provided")
                          }
                        }
                        if (is.null(value)) {
                          private$params[id] <- list(NULL)
                        } else {
                          private$params[[id]]=value
                        }
                        if (description=="") {
                          if (!(id %in% names(private$descriptions))) { # provide tautological definition if 
                            description=paste0("The value of ", id, " is {", id, "}")
                          } else {
                            description=private$descriptions[id]}
                        } 
                        description <- sub("\\{\\}", paste0("{", id, "}"), description)
                        private$descriptions[[id]]=description
                        if (div & isTRUE(getOption('knitr.in.progress'))) {
#                          cat(knitr::knit_child(text=knitr::knit_expand(text=c("```{block, type='rparam'}", self$describe(id), "```")), quiet=TRUE))
                          cat("\n\n<div class=\"rparam\">", self$describe(id), "</div>\n\n")
                        }
                        invisible(self$get(id))
                      },
                      get = function(id) {
                        ret <- private$params[[id]]
                        if (is.call(ret)) eval(ret) else ret
                      },
                      describe = function(id) {
                        if (missing(id)) {
                          map(private$descriptions[names(private$params)],  function(d) glue::glue_data(.x =private$params, d))
                        } else {
                          glue::glue_data(private$params,
                                          private$descriptions[[id]])
                        }
                      }
                    )
                    )
